#!/bin/sh
### BEGIN INIT INFO
# Provides:          CCM
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Run /etc/rc.local if it exists
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

do_start() {
    echo "nameserver 8.8.8.8" > /etc/resolv.conf
    /bin/ssh-keygen -A
    /etc/init.d/ssh restart
    /bin/desmonta_home.sh 2>&1 | ts '[%Y-%m-%d %H:%M:%S]' >> /var/log/desmonta_home.log
    /usr/bin/vmware-modconfig --console --install-all


    if [ -x /etc/rc.local ]; then
        [ "$VERBOSE" != no ] && log_begin_msg "Running local boot scripts (/etc/rc.local)"
        /etc/rc.local
        ES=$?
        [ "$VERBOSE" != no ] && log_end_msg $ES
        return $ES
    fi
}

case "$1" in
    start)
        do_start
        vmware-modconfig --console --install-all
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac

exit 0